### ISSUE TITLE
Something wrong happens

### ISSUE THREAD

**Issue by erykpiast** [izifortune/lighthouse-keeper#1]
I cannot make it working for some reason, getting red error message when trying to upload reports recorded in Chrome 69.

[amazon_listing.json.zip](https://github.com/izifortune/lighthouse-keeper/files/2119120/amazon_listing.json.zip)
[ebay_listing.json.zip](https://github.com/izifortune/lighthouse-keeper/files/2119121/ebay_listing.json.zip)

Browser (where I launch the app): Chrome 67.0
OS: Mac OS 10.13.5

**Comment by izifortune** [comment]
Hi @erykpiast, I'm having a look into this. Thanks for reporting it

**Comment by izifortune** [comment]
I've checked the json file that you are using and those are based upon lighthouse v3. lighthouse-keeper at the moment support only v2.

I'm planning to support v3 very soon.

Thanks for your feedback @erykpiast

**Comment by erykpiast** [comment]
Your welcome! How big these differences are? Maybe I could help?

**Comment by izifortune** [comment]
Hi @erykpiast, I've updated the application to support v3 now. Can you please confirm that it is working for you?

**Comment by addyosmani** [comment]
Hey @izifortune. I've been testing Lighthouse reports from V3.x and unfortunately the same issue above is persisting. You might find it useful to test against the latest version of Lighthouse we have in the Canary DevTools or the output from Lighthouse on WebPageTest as both should be using the latest versions of the report.
