### ISSUE TITLE
Total weight result is not correct

### ISSUE THREAD

**Issue by cxq** [izifortune/lighthouse-keeper#3]
Hi,

I've started implementing the performance budget tool based on Lighthouse for my projects. I was googling to see whether I could reuse what you have done and noticed that the graphs you are generating are not correct and especially the one regarding the total weight. If I'm not mistaken you should use the property `network-requests` instead of `total-byte-weight`.

Cheers,
Xiu

**Comment by cxq** [comment]
In my opinion having a budget for XHR/Fetch doesn't make really sense. Usually when you try to implement performance budget in a company they would not all necessarily understand what it is. I mean "non" technical teams.  

I'd rather have a category "Other".

**Comment by izifortune** [comment]
Yes probably this apply only to a subset of web development projects
specifically web apps. I can group also the other types into other ( which
are not displayed at the moment )

**Comment by izifortune** [comment]
@cxq  I've merged the PR should be fixed now. Please reopen if you find any issues
