### ISSUE TITLE
Something wrong happens (v4)

### ISSUE THREAD

**Issue by klokie** [izifortune/lighthouse-keeper#5]
Hi, this looks like a promising project, but for me it doesn't work with the latest version of Lighthouse (4.2), just "Oops something wrong happened!!"

I can send you my JSON reports if that would be helpful?

**Comment by izifortune** [comment]
Hi @klokie  I've updated to v4 reports. The last update was for v3. Can you please confirm that the error is not present anymore?

**Comment by klokie** [comment]
works great now, thanks!
